### ISSUE TITLE
C# Generation failure with `FFISlice<CStrPointer>`

### ISSUE THREAD

**Issue by nikita-island** [ralfbiedert/interoptopus#121]
Hello,

First of all, thanks for the library!

I'm getting C# errors in generated bindings and I'm wondering if it's a bug or if I'm not using the library in the intended way.
I'm using the latest version:
```toml
[package]
name = "bla"
version = "0.1.0"
edition = "2021"

[dependencies]
interoptopus = { git = "https://github.com/ralfbiedert/interoptopus.git", branch = "master" }
interoptopus_backend_csharp = { git = "https://github.com/ralfbiedert/interoptopus.git", branch = "master" }
```

I tried to create a function the receives an array of strings:
```rust
use interoptopus::{
    ffi_function,
    patterns::{slice::FFISlice, string::CStrPointer},
    Interop, InventoryBuilder,
};
use interoptopus_backend_csharp::overloads::DotNet;

#[ffi_function]
extern "C" fn slice_of_strings(param: FFISlice<CStrPointer>) {}

fn main() {
    interoptopus_backend_csharp::Generator::new(
        interoptopus_backend_csharp::Config::default(),
        InventoryBuilder::new()
            .register(interoptopus::function!(slice_of_strings))
            .inventory(),
    )
    .add_overload_writer(DotNet::new())
    .write_file("/dev/stdout")
    .unwrap();
}
```

I get the following C# result:
```c#
// ...
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "slice_of_strings")]
        public static extern void slice_of_strings(Slice*const i8 param);

        public static void slice_of_strings(string[] param)
        {
            var param_pinned = GCHandle.Alloc(param, GCHandleType.Pinned);
            var param_slice = new Slice*const i8(param_pinned, (ulong) param.Length);
            try
            {
                slice_of_strings(param_slice);;
            }
            finally
            {
                param_pinned.Free();
            }
        }

    }

    ///A pointer to an array of data someone else owns which may not be modified.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Slice*const i8
    {
        ///Pointer to start of immutable data.
        IntPtr data;
        ///Number of elements.
        ulong len;
    }

    public partial struct Slice*const i8 : IEnumerable<IntPtr>
    {
        public Slice*const i8(GCHandle handle, ulong count)
        {
            this.data = handle.AddrOfPinnedObject();
// ...
```

Note the various **`Slice*const i8`** sprinkled throughout the generated code. Interestingly, the C# overload gets generated correctly (`public static void slice_of_strings(string[] param)`).
